"use client";

export default function DemoPosterPage() {
  return (
    <div style={{ padding: '3rem 1.5rem', maxWidth: '1200px', margin: '0 auto', width: '100%' }}>
      <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
        <h1 style={{ fontSize: '2.5rem', fontWeight: 800, color: '#fff', marginBottom: '0.5rem', letterSpacing: '-1px' }}>Automated Posters</h1>
        <p style={{ color: '#94a3b8', fontSize: '1.1rem', maxWidth: '600px', margin: '0 auto' }}>
          When a program result is published, the system instantly generates a stunning, branded poster ready for Instagram and WhatsApp.
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '4rem', alignItems: 'center' }}>
        
        {/* Mock Poster Output */}
        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <div style={{ 
            width: '400px', 
            height: '500px', 
            background: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)', 
            borderRadius: '0', 
            position: 'relative',
            boxShadow: '0 25px 50px -12px rgba(0,0,0,0.5)',
            border: '8px solid #000',
            overflow: 'hidden'
          }}>
            {/* Poster Decorations */}
            <div style={{ position: 'absolute', top: '-50px', right: '-50px', width: '150px', height: '150px', background: '#8b5cf6', filter: 'blur(40px)', opacity: 0.5 }}></div>
            <div style={{ position: 'absolute', bottom: '-50px', left: '-50px', width: '200px', height: '200px', background: '#ec4899', filter: 'blur(50px)', opacity: 0.4 }}></div>
            
            <div style={{ position: 'relative', zIndex: 1, padding: '2.5rem', height: '100%', display: 'flex', flexDirection: 'column' }}>
              <div style={{ textAlign: 'center', marginBottom: '2rem' }}>
                <div style={{ fontSize: '0.8rem', color: '#cbd5e1', textTransform: 'uppercase', letterSpacing: '2px', marginBottom: '0.5rem' }}>CSWC Hiya Fiesta 2026</div>
                <h2 style={{ fontSize: '2rem', color: '#fff', fontWeight: 900, margin: 0, lineHeight: 1.1, textTransform: 'uppercase' }}>Classical Dance</h2>
                <div style={{ fontSize: '0.9rem', color: '#a78bfa', marginTop: '0.25rem' }}>Category: Senior Level</div>
              </div>

              <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '1.5rem' }}>
                
                {/* 1st Place */}
                <div style={{ background: 'rgba(255,255,255,0.1)', backdropFilter: 'blur(10px)', padding: '1rem', borderRadius: '12px', border: '1px solid rgba(255,255,255,0.2)', display: 'flex', alignItems: 'center', gap: '1rem' }}>
                  <div style={{ fontSize: '2rem' }}>🥇</div>
                  <div>
                    <div style={{ color: '#fff', fontWeight: 800, fontSize: '1.2rem' }}>Aisha M.</div>
                    <div style={{ color: '#cbd5e1', fontSize: '0.85rem' }}>Team Alpha</div>
                  </div>
                </div>

                {/* 2nd Place */}
                <div style={{ background: 'rgba(255,255,255,0.05)', backdropFilter: 'blur(10px)', padding: '0.8rem 1rem', borderRadius: '12px', border: '1px solid rgba(255,255,255,0.1)', display: 'flex', alignItems: 'center', gap: '1rem' }}>
                  <div style={{ fontSize: '1.5rem' }}>🥈</div>
                  <div>
                    <div style={{ color: '#f8fafc', fontWeight: 700, fontSize: '1rem' }}>Rohan K.</div>
                    <div style={{ color: '#94a3b8', fontSize: '0.8rem' }}>Team Bravo</div>
                  </div>
                </div>

                 {/* 3rd Place */}
                 <div style={{ background: 'rgba(255,255,255,0.05)', backdropFilter: 'blur(10px)', padding: '0.8rem 1rem', borderRadius: '12px', border: '1px solid rgba(255,255,255,0.1)', display: 'flex', alignItems: 'center', gap: '1rem' }}>
                  <div style={{ fontSize: '1.5rem' }}>🥉</div>
                  <div>
                    <div style={{ color: '#f8fafc', fontWeight: 700, fontSize: '1rem' }}>Meera S.</div>
                    <div style={{ color: '#94a3b8', fontSize: '0.8rem' }}>Team Charlie</div>
                  </div>
                </div>

              </div>

              <div style={{ textAlign: 'center', marginTop: 'auto', paddingTop: '1rem', borderTop: '1px solid rgba(255,255,255,0.1)' }}>
                <span style={{ fontSize: '0.7rem', color: '#94a3b8', letterSpacing: '1px' }}>GENERATED BY CSWC SYSTEM</span>
              </div>
            </div>
          </div>
        </div>

        {/* Generator Controls */}
        <div>
          <div style={{ background: 'rgba(255,255,255,0.02)', padding: '2.5rem', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.05)' }}>
            <h3 style={{ color: '#fff', fontSize: '1.5rem', marginTop: 0, marginBottom: '2rem' }}>Poster Settings</h3>
            
            <div style={{ marginBottom: '1.5rem' }}>
              <label style={{ display: 'block', color: '#94a3b8', fontSize: '0.9rem', marginBottom: '0.5rem' }}>Select Theme</label>
              <div style={{ display: 'flex', gap: '1rem' }}>
                <button style={{ flex: 1, padding: '0.75rem', background: '#312e81', border: '2px solid #8b5cf6', borderRadius: '8px', color: '#fff', fontWeight: 600, cursor: 'pointer' }}>Neon Dark</button>
                <button style={{ flex: 1, padding: '0.75rem', background: '#f8fafc', border: '1px solid #cbd5e1', borderRadius: '8px', color: '#0f172a', fontWeight: 600, cursor: 'pointer' }}>Clean Light</button>
              </div>
            </div>

            <div style={{ marginBottom: '2rem' }}>
              <label style={{ display: 'block', color: '#94a3b8', fontSize: '0.9rem', marginBottom: '0.5rem' }}>Aspect Ratio</label>
              <div style={{ display: 'flex', gap: '1rem' }}>
                <button style={{ flex: 1, padding: '0.75rem', background: 'rgba(56, 189, 248, 0.1)', border: '1px solid #38bdf8', borderRadius: '8px', color: '#38bdf8', fontWeight: 600, cursor: 'pointer' }}>4:5 (Instagram)</button>
                <button style={{ flex: 1, padding: '0.75rem', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px', color: '#fff', fontWeight: 600, cursor: 'pointer' }}>16:9 (Story)</button>
              </div>
            </div>

            <button style={{ width: '100%', padding: '1rem', background: 'linear-gradient(135deg, #8b5cf6 0%, #a855f7 100%)', color: '#fff', border: 'none', borderRadius: '12px', fontSize: '1.1rem', fontWeight: 700, cursor: 'pointer', boxShadow: '0 4px 15px rgba(139, 92, 246, 0.3)' }}>
              Download Poster Image
            </button>
            <p style={{ textAlign: 'center', color: '#64748b', fontSize: '0.85rem', marginTop: '1rem', margin: '1rem 0 0 0' }}>
              (Mock interaction - buttons are for display only)
            </p>
          </div>
        </div>

      </div>
    </div>
  );
}
